// Worksheet 4 exercises — generated by generate.js
// Source: gyakorlas_4_megoldasok_cl.docx
const EXERCISES_W4 = [
  {
    "id": "w4_01",
    "w": 4,
    "topic": "Alapfogalmak",
    "type": "mc",
    "q": "Mit jelent a 'hiányosság' (deficiență) fogalma az orvosi modell szerint?",
    "opts": [
      "Az egyén és a környezet kölcsönhatásából eredő funkcionális korlátok összessége",
      "Szervi vagy funkcionális szintű eltérés, károsodás az egyén biológiai struktúráiban",
      "Olyan oktatási kategória, amely személyre szabott pedagógiai támogatást igényel",
      "A sérült funkciók ellensúlyozására irányuló fejlődési folyamat"
    ],
    "ans": 1,
    "exp": "A hiányosság (deficiență) az orvosi modell szerinti legalsó szint: szervi vagy funkcionális szintű eltérés, károsodás, amely az egyén biológiai struktúráiban vagy funkcióiban jelenik meg.",
    "diff": 1
  },
  {
    "id": "w4_02",
    "w": 4,
    "topic": "Alapfogalmak",
    "type": "mc",
    "q": "A modern biopszicho-szociális modell szerint a fogyatékosság hol keletkezik?",
    "opts": [
      "Kizárólag az egyén biológiai struktúráiban",
      "A genetikai rendellenességek következtében",
      "A személy és az akadályozó környezet találkozásában",
      "A pedagógiai értékelési folyamat eredményeként"
    ],
    "ans": 2,
    "exp": "A modern biopszicho-szociális modell szerint a fogyatékosság nem kizárólag az egyénben, hanem a személy és az akadályozó környezet találkozásában keletkezik.",
    "diff": 1
  },
  {
    "id": "w4_03",
    "w": 4,
    "topic": "Alapfogalmak",
    "type": "tf",
    "q": "Vigotszkij értelmezésében a kompenzáció automatikusan zajlik le, és nem igényel nevelői beavatkozást.",
    "ans": false,
    "exp": "Ez hamis. Vigotszkij szerint a kompenzáció nem automatikusan zajlik – megfelelő nevelői beavatkozást igényel a sértetlen funkciók mozgósításához és fejlesztéséhez.",
    "diff": 1
  },
  {
    "id": "w4_04",
    "w": 4,
    "topic": "Alapfogalmak",
    "type": "mc",
    "q": "Mi a különbség a habilitáció és a rehabilitáció között?",
    "opts": [
      "A habilitáció elveszített funkciók visszaállítására, a rehabilitáció soha nem létezett készségek kialakítására irányul",
      "A habilitáció soha nem fejlődött készségek kialakítását, a rehabilitáció korábban meglévő funkciók visszaállítását jelenti",
      "Mindkettő elveszített funkciók visszaállítására irányul, csak különböző módszerekkel",
      "A habilitáció és a rehabilitáció azonos fogalmak, csupán más kontextusban használják őket"
    ],
    "ans": 1,
    "exp": "A habilitáció olyan képességek kialakítását jelenti, amelyek soha nem fejlődtek ki (pl. veleszületett siketségnél kommunikációs készség), míg a rehabilitáció korábban meglévő, majd elveszített funkciók visszaállítására irányul (pl. stroke utáni beszédterápia).",
    "diff": 1
  },
  {
    "id": "w4_05",
    "w": 4,
    "topic": "Alapfogalmak",
    "type": "fill",
    "q": "A CES (Sajátos nevelési igény) egy olyan oktatási kategória, amely szélesebb, mint a fogyatékosság, és magában foglalhatja a tanulási zavarokat, a magatartási nehézségeket és a ____ hátrányból eredő igényeket is.",
    "ans": "szociális",
    "exp": "A CES szélesebb kategória, mint a fogyatékosság – magában foglalhatja a tanulási zavarokat, a magatartási nehézségeket és a szociális hátrányból eredő igényeket is.",
    "diff": 1
  },
  {
    "id": "w4_06",
    "w": 4,
    "topic": "Pszichopedagógia specialis kapcsolatai",
    "type": "match",
    "q": "Párosítsa össze a pszichopedagógia specialis kapcsolódó tudományát a megfelelő hozzájárulásával!",
    "pairs": [
      {
        "L": "Pszichológia",
        "R": "Kognitív, érzelmi és szociális fejlődés megértéséhez szükséges elméleti keretek biztosítása"
      },
      {
        "L": "Orvostudomány",
        "R": "Etiológia, diagnózis és gyógyszeres kezelés területén nyújt nélkülözhetetlen partneri szerepet"
      },
      {
        "L": "Szociológia",
        "R": "A kirekesztés és befogadás mechanizmusai, a fogyatékosság szociális modellje"
      },
      {
        "L": "Logopédia",
        "R": "Kommunikációs és nyelvi fejlesztés, augmentatív kommunikáció, ASD tanulók kommunikációs fejlesztése"
      }
    ],
    "exp": "A pszichopedagógia specialis négy társtudománya: a pszichológia (fejlődési keretek), az orvostudomány (etiológia, diagnózis), a szociológia (befogadás, kirekesztés mechanizmusai) és a logopédia (kommunikációs fejlesztés).",
    "diff": 2
  },
  {
    "id": "w4_07",
    "w": 4,
    "topic": "Pszichopedagógia specialis feladatai",
    "type": "mc",
    "q": "Melyik NEM tartozik a pszichopedagógia specialis négy alapvető feladata közé?",
    "opts": [
      "Megismerő-értékelő feladat",
      "Tervező és intervenciós feladat",
      "Megelőző feladat",
      "Gyógyszeres terápia alkalmazása"
    ],
    "ans": 3,
    "exp": "A négy alapvető feladat: megismerő-értékelő, tervező és intervenciós, megelőző, valamint kutatás és szakmaközi együttműködés. A gyógyszeres terápia alkalmazása az orvostudomány feladata, nem a pszichopedagógiáé.",
    "diff": 1
  },
  {
    "id": "w4_08",
    "w": 4,
    "topic": "Komplex integrált oktatási terápia",
    "type": "mc",
    "q": "Mi jellemzi a komplex, integrált oktatási terápia jellegét?",
    "opts": [
      "A tantárgyak és a terápiás foglalkozások párhuzamosan, egymástól függetlenül futnak",
      "A terápiás elemek beépülnek az oktatási tevékenységekbe, és azok szerves integrációját valósítják meg",
      "Kizárólag a logopédiai fejlesztésre összpontosít, más területeket nem érint",
      "A fejlesztés mozzanatai vagy pedagógiai, vagy terápiás értékkel bírnak, de egyszerre soha"
    ],
    "ans": 1,
    "exp": "A komplex, integrált oktatási terápia nem a tantárgyak és terápiás foglalkozások párhuzamos futtatását jelenti, hanem azok szerves integrációját: a terápiás elemek beépülnek az oktatási tevékenységekbe, és fordítva.",
    "diff": 1
  },
  {
    "id": "w4_09",
    "w": 4,
    "topic": "Komplex integrált oktatási terápia",
    "type": "mc",
    "q": "Melyik terápiás modul foglalkozik a testséma, a térbeli tájékozódás és az önkiszolgálási készségek fejlesztésével?",
    "opts": [
      "Kognitív stimulációs és tanulástámogatási modul",
      "Kommunikációs és logopédiai modul",
      "Pszichomotoros és foglalkozásterápiás modul",
      "Szocioemocionális és viselkedéstámogató modul"
    ],
    "ans": 2,
    "exp": "A pszichomotoros és foglalkozásterápiás modul foglalkozik a nagy- és finommotorika, a testséma, a térbeli tájékozódás és az önkiszolgálási készségek fejlesztésével.",
    "diff": 1
  },
  {
    "id": "w4_10",
    "w": 4,
    "topic": "Terápiás tevékenységek oktatási értékei",
    "type": "mc",
    "q": "A dramatikus játék / szerepjáték tevékenység melyik területeket fejleszti egyszerre?",
    "opts": [
      "Kizárólag a mozgáskoordinációt és a finommotorikát",
      "A szociális kommunikációs készségeket, szókincsgyarapítást, perspektívafelvételt és érzelemszabályozást",
      "Csak az auditív figyelmet és a sorrendiséget",
      "Kizárólag a betű-hang kapcsolatot és a vizuális emlékezetet"
    ],
    "ans": 1,
    "exp": "A dramatikus játék / szerepjáték egyszerre fejleszti a szociális kommunikációs készségeket (kérés, köszönés, turnusváltás), a szókincsgyarapítást, a perspektívafelvételt és az érzelemszabályozást.",
    "diff": 2
  },
  {
    "id": "w4_11",
    "w": 4,
    "topic": "Multidiszciplináris team",
    "type": "mc",
    "q": "Melyik a szociális munkás feladata a multidiszciplináris teamben?",
    "opts": [
      "A kommunikációs és nyelvi zavarok diagnosztikája és terápiája",
      "A PIP kidolgozása és megvalósítása az osztályban",
      "A tanuló és a család szociális helyzetének felmérése és szociális szolgáltatásokhoz való hozzáférés biztosítása",
      "A tanuló érzelmi és kognitív funkcionálásának értékelése"
    ],
    "ans": 2,
    "exp": "A szociális munkás feladata a tanuló és a család szociális helyzetének felmérése, szociális szolgáltatásokhoz való hozzáférés biztosítása, a veszélyeztetett tanulók védelmének koordinálása és a közösségi erőforrások mozgósítása.",
    "diff": 1
  },
  {
    "id": "w4_12",
    "w": 4,
    "topic": "Multidiszciplináris team",
    "type": "tf",
    "q": "A multidiszciplináris team etikai elvei szerint a tanuló értékelési eredményeit harmadik félnek kiadhatók a szülők szóbeli beleegyezésével is.",
    "ans": false,
    "exp": "Ez hamis. A titoktartás és adatvédelem elve szerint harmadik félnek csak a szülők ÍRÁSOS beleegyezésével adható ki az értékelési eredmény és a fejlesztési terv tartalma.",
    "diff": 2
  },
  {
    "id": "w4_13",
    "w": 4,
    "topic": "Nyelv, beszéd, nyelvi zavar",
    "type": "mc",
    "q": "Hogyan definiálható a 'beszéd' fogalma?",
    "opts": [
      "Társadalmilag kialakult, szabályrendszer által meghatározott szimbolikus kommunikációs rendszer",
      "A nyelv megértésének és produkciójának tartós nehézsége",
      "A nyelv hangzó megvalósítása; kommunikációs szándék artikulált, akusztikai formában való kivetítése",
      "Az emberi kommunikáció elvont, mentális reprezentációja"
    ],
    "ans": 2,
    "exp": "A beszéd a nyelv hangzó megvalósítása; a kommunikációs szándék artikulált, akusztikai formában való kivetítése. Egyéni, motorikus tevékenység, amelynek során az egyén légzési, fonációs és artikulációs mechanizmusok összehangolt működésével produkál hangokat.",
    "diff": 1
  },
  {
    "id": "w4_14",
    "w": 4,
    "topic": "Nyelvi zavartípusok",
    "type": "match",
    "q": "Párosítsa össze a nyelvi zavartípust a megfelelő megközelítési szemponttal!",
    "pairs": [
      {
        "L": "Dysarthria",
        "R": "Anatómiai-fiziológiai szempont – neurológiai károsodás következtében kialakult motorikus beszédzavar"
      },
      {
        "L": "Specifikus nyelvi zavar (SLI/DLD)",
        "R": "Nyelvészeti szempont – grammatikai struktúrák elsajátításának tartós zavara normál kognitív fejlődés mellett"
      },
      {
        "L": "Afázia",
        "R": "Etiológiai szempont – korábban normálisan fejlett nyelvhasználat elvesztése agyi sérülés következtében"
      },
      {
        "L": "Elektív mutizmus",
        "R": "Pszichológiai szempont – szorongásos alapú állapot, bizonyos szociális helyzetekben való megszólalás képtelensége"
      }
    ],
    "exp": "A négy zavartípus különböző szempontok szerint: Dysarthria (anatómiai-fiziológiai), SLI/DLD (nyelvészeti), Afázia (etiológiai), Elektív mutizmus (pszichológiai).",
    "diff": 2
  },
  {
    "id": "w4_15",
    "w": 4,
    "topic": "Nyelvi zavarok CES tanulóknál",
    "type": "mc",
    "q": "Mi jellemzi a pragmatikai zavart ASD esetén?",
    "opts": [
      "A szókincs szűkössége és az egyszerű mondatszerkezetek használata",
      "Az artikulációs izmok gyengesége és a hangok torzítása",
      "A kölcsönös párbeszéd fenntartásának, a metaforák értelmezésének és a kommunikációs kontextus rugalmas alkalmazásának nehézsége",
      "A hangzó beszéd teljes hiánya minden szociális helyzetben"
    ],
    "ans": 2,
    "exp": "ASD esetén a pragmatikai zavar – a nyelv szociális használatának zavara – az egyik meghatározó jellemző: a gyermeknek nehézséget okoz a kölcsönös párbeszéd fenntartása, a metaforák értelmezése, a nem szó szerinti tartalmak megértése és a kommunikációs kontextus rugalmas alkalmazása.",
    "diff": 2
  },
  {
    "id": "w4_16",
    "w": 4,
    "topic": "Artikulációs zavar terápiája",
    "type": "order",
    "q": "Rendezze helyes sorrendbe az artikulációs zavar terápiájának öt szakaszát!",
    "items": [
      "Differenciálási szakasz – a célhang megkülönböztetése hasonló hangoktól",
      "Hangkialakítási szakasz – a hiányzó vagy torzított hang helyes képzésének megtanítása",
      "Előkészítő szakasz – auditív diszkrimináció, figyelmi és légzési funkciók fejlesztése",
      "Automatizálási szakasz – a hang beépítése a spontán, folyamatos beszédbe",
      "Rögzítési szakasz – a helyesen kialakított hang stabillá tétele szótagokban és szavakban"
    ],
    "exp": "A helyes sorrend: 1. Előkészítő szakasz, 2. Hangkialakítási szakasz, 3. Rögzítési szakasz, 4. Differenciálási szakasz, 5. Automatizálási szakasz.",
    "diff": 2
  },
  {
    "id": "w4_17",
    "w": 4,
    "topic": "Artikulációs zavar terápiája",
    "type": "mc",
    "q": "Mit céloz a differenciálási szakasz az artikulációs zavar terápiájában?",
    "opts": [
      "Az artikulációs szervek előkészítő mozgatásának megtanítását",
      "A célhang megkülönböztetését a hozzá hasonló, korábban összekevert hangoktól",
      "A hang beépítését a spontán, folyamatos beszédbe",
      "A helyes hangképzés módjának bemutatását tükör előtt"
    ],
    "ans": 1,
    "exp": "A differenciálási szakaszban a célhangot megkülönböztetik a hasonló, korábban összekevert hangoktól (pl. sz–s, r–l). A tanuló azonosítja és szétválasztja a két hangot szavakban és mondatokban – auditív diszkriminációs és produkciós feladatokkal.",
    "diff": 2
  },
  {
    "id": "w4_18",
    "w": 4,
    "topic": "Megkésett nyelvfejlődés",
    "type": "mc",
    "q": "Az augmentatív kommunikáció (pl. PECS) korai bevezetéséről melyik állítás igaz?",
    "opts": [
      "Az AAC bevezetése akadályozza a hangzó beszéd fejlődését",
      "Az AAC kizárólag nem verbális felnőttek számára alkalmazható",
      "Az AAC nem akadályozza, hanem elősegíti a hangzó beszéd fejlődését, csökkenti a kommunikációs frusztrációt",
      "Az AAC csak magas technológiájú eszközökkel alkalmazható hatékonyan"
    ],
    "ans": 2,
    "exp": "Kutatások egyértelműen igazolják, hogy az AAC bevezetése nem akadályozza, hanem elősegíti a hangzó beszéd fejlődését, mivel csökkenti a kommunikációs frusztrációt és növeli a motivációt.",
    "diff": 2
  },
  {
    "id": "w4_19",
    "w": 4,
    "topic": "Augmentatív és alternatív kommunikáció",
    "type": "mc",
    "q": "Melyik NEM szerepel az AAC három kommunikációs funkciója között a kérésen kívül?",
    "opts": [
      "Elutasítás és tiltakozás",
      "Kommentálás és véleménynyilvánítás",
      "Információkérés",
      "Gyógyszeres kezelés jelzése"
    ],
    "ans": 3,
    "exp": "A három kommunikációs funkció a kérésen kívül: elutasítás és tiltakozás, kommentálás és véleménynyilvánítás, valamint információkérés. A gyógyszeres kezelés jelzése nem szerepel az AAC kommunikációs funkciói között.",
    "diff": 1
  },
  {
    "id": "w4_20",
    "w": 4,
    "topic": "Hagyományos és aktív módszerek",
    "type": "mc",
    "q": "Melyik jellemző különbözteti meg az aktív-részvételi módszereket a hagyományos módszerektől?",
    "opts": [
      "A pedagógus áll a tanítási folyamat középpontjában, és egyirányúan közvetíti az információt",
      "A tudás felfedezésen, együttműködésen és saját tapasztalaton keresztül épül fel, a tanuló aktív résztvevő",
      "A memorizálás és a tudásátadás kap kizárólagos hangsúlyt",
      "A tanuló elsősorban befogadó szerepben van"
    ],
    "ans": 1,
    "exp": "Az aktív-részvételi módszereknél a tanuló aktív, cselekvő résztvevője a tanulási folyamatnak; a tudás felfedezésen, együttműködésen és saját tapasztalaton keresztül épül fel. A pedagógus facilitátorként vesz részt.",
    "diff": 1
  },
  {
    "id": "w4_21",
    "w": 4,
    "topic": "Módszertani adaptáció",
    "type": "mc",
    "q": "Hogyan kell adaptálni a magyarázat módszerét ADHD-val élő tanuló számára?",
    "opts": [
      "A magyarázat hosszát növelni kell, hogy minden részlet elhangozzon egyszerre",
      "A magyarázatot max. 5–7 perces egységekre kell bontani, aktív elemeket kell beépíteni, és vizuálisan kiemelkedő eszközöket kell alkalmazni",
      "A tanuló passzív megfigyelő szerepét kell megerősíteni, hogy jobban összpontosíthasson",
      "Az elvont, szóbeli ismertetést kell előtérbe helyezni a konkrét szemléltetés helyett"
    ],
    "ans": 1,
    "exp": "ADHD esetén a magyarázat max. 5–7 perces legyen, amelyet aktív elemet tartalmazó szünet követ. A pedagógus előre elmondja a struktúrát, a tanuló aktív szerepet kap (táblára ír, visszamond), és vizuálisan kiemelkedő eszközök segítenek.",
    "diff": 2
  },
  {
    "id": "w4_22",
    "w": 4,
    "topic": "Kooperatív tanulás adaptálása",
    "type": "mc",
    "q": "Hogyan kell adaptálni a Jigsaw (Puzzle) technikát autizmus spektrumon lévő tanuló számára?",
    "opts": [
      "A csoporttagok számát növelni kell a szociális fejlesztés érdekében",
      "A szerepeket és feladatlépéseket előre részletesen kell elmagyarázni, vizuálisan rögzíteni, és kisebb csoportokat (2–3 fő) kell alkalmazni",
      "A feladatlépéseket nem kell előre ismertetni, hogy a tanuló alkalmazkodóképessége fejlődjön",
      "A szenzoros ingerek maximalizálása javasolt a motiváció növelése érdekében"
    ],
    "ans": 1,
    "exp": "ASD tanulóknál a szerepeket és feladatlépéseket előre részletesen kell elmagyarázni és vizuálisan rögzíteni (lépéskártyák), kisebb csoportokat (2–3 fő) kell alkalmazni, és csendesebb munkakörnyezetet kell biztosítani a szenzoros túlterhelés megelőzésére.",
    "diff": 2
  },
  {
    "id": "w4_23",
    "w": 4,
    "topic": "Speciális oktatási módszerek",
    "type": "mc",
    "q": "Mit jelent a 'visszatartó láncolás' (backward chaining) a feladatelemzés kontextusában?",
    "opts": [
      "A tanuló az első lépéstől halad az utolsó felé, és először csak az első lépést végzi önállóan",
      "A tanuló mindig az utolsó lépésnél él át sikerélményt, majd fokozatosan veszi át a korábbi lépések felelősségét",
      "A pedagógus minden lépést elvégez, és a tanuló csak megfigyel",
      "A feladatlépések véletlenszerű sorrendben kerülnek megtanításra"
    ],
    "ans": 1,
    "exp": "A visszatartó láncolás (backward chaining) esetén a tanuló mindig az utolsó lépésnél él át sikerélményt, majd fokozatosan veszi át a korábbi lépések felelősségét is. Ez ellentéte az előretartó láncolásnak.",
    "diff": 2
  },
  {
    "id": "w4_24",
    "w": 4,
    "topic": "Speciális oktatási eszközök",
    "type": "mc",
    "q": "Milyen célra alkalmaznak súlyozott takarókat és rezgő párnákat a speciális oktatásban?",
    "opts": [
      "Az olvasás-írás előkészítésére és a betű-hang kapcsolat fejlesztésére",
      "ASD és szenzoros feldolgozási zavarral élő tanulók idegrendszerének szabályozásához",
      "A matematikai fogalmak vizuális bemutatásához",
      "A kommunikációs szándékok képszimbólumokkal való közvetítéséhez"
    ],
    "ans": 1,
    "exp": "A súlyozott takarók, rezgő párnák és textúrázott felületek érzékszervi integrációs eszközök, amelyeket ASD és szenzoros feldolgozási zavarral élő tanulók idegrendszerének szabályozásához alkalmaznak.",
    "diff": 1
  },
  {
    "id": "w4_25",
    "w": 4,
    "topic": "Speciális oktatási eszközök",
    "type": "mc",
    "q": "Melyik eszköz ajánlott diszgráfiával küzdő vagy finommotoros nehézséggel rendelkező tanulók számára?",
    "opts": [
      "Kommunikációs táblák és PECS-kártyák",
      "Súlyozott takarók és rezgő párnák",
      "Adaptált írástámogató eszközök (háromszög ceruzafogók, lejtős írófelületek)",
      "Tablet alapú kommunikációs alkalmazások"
    ],
    "ans": 2,
    "exp": "Az adaptált írástámogató eszközök – háromszög keresztmetszetű ceruzafogók, lejtős írófelületek, vonalas segédlapok, vastag markolatú ceruzák – finommotoros nehézséggel vagy diszgráfiával küzdő tanulók számára ajánlottak.",
    "diff": 1
  },
  {
    "id": "w4_26",
    "w": 4,
    "topic": "Terápiás tevékenységek oktatási értékei",
    "type": "fill",
    "q": "A ritmus- és zenei tevékenységek fejlesztik az auditív figyelmet, a sorrendiséget, a munkamemóriát és a mozgáskoordinációt, amelyek mind nélkülözhetetlen előfeltételei az ____ tanulásának.",
    "ans": "olvasás-írás",
    "exp": "A ritmus- és zenei tevékenységek olyan alapfunkciókat fejlesztenek (auditív figyelem, sorrendiség, munkamemória, mozgáskoordináció), amelyek az olvasás-írás tanulásának nélkülözhetetlen előfeltételei.",
    "diff": 1
  },
  {
    "id": "w4_27",
    "w": 4,
    "topic": "Megkésett nyelvfejlődés",
    "type": "mc",
    "q": "Melyik sztenderdizált eszközök alkalmazhatók a megkésett nyelvfejlődés diagnosztikájában?",
    "opts": [
      "PECS-kártyák és kommunikációs táblák",
      "REYNELL és MacArthur–Bates kommunikatív fejlődési skálák",
      "Súlyozott takarók és érzékszervi integrációs eszközök",
      "Adaptált ceruzafogók és lejtős írófelületek"
    ],
    "ans": 1,
    "exp": "A megkésett nyelvfejlődés diagnosztikájában sztenderdizált eszközként a REYNELL és a MacArthur–Bates kommunikatív fejlődési skálák, valamint strukturált megfigyelés alkalmazandó.",
    "diff": 2
  },
  {
    "id": "w4_28",
    "w": 4,
    "topic": "Logopédiai módszerek",
    "type": "mc",
    "q": "Mit céloz a Schultze-módszer (tükörfogásos gyakorlat) a logopédiában?",
    "opts": [
      "A fonémtudatosság fejlesztését és a hangszintézis-képesség kialakítását",
      "Az orrüreg és szájüreg levegőáram-irányításának tudatosítását rhinolalia esetén",
      "A hangkialakítást tükör előtt, tapintásos visszajelzéssel",
      "Az auditív diszkrimináció fejlesztését és a célhang felismerését"
    ],
    "ans": 1,
    "exp": "A Schultze-módszer (tükörfogásos gyakorlat) nazális rezonancia fejlesztésére, orrhangzósítással kapcsolatos kiejtési zavaroknál (pl. rhinolalia) alkalmazott módszer, amely a levegőáram helyes irányítását és az orrüreg/szájüreg elválasztásának tudatosítását célozza.",
    "diff": 2
  },
  {
    "id": "w4_29",
    "w": 4,
    "topic": "Alapfogalmak",
    "type": "tf",
    "q": "A CES (Sajátos nevelési igény) kategória azonos a fogyatékossággal, ezért csak fogyatékossággal diagnosztizált tanulók tartozhatnak bele.",
    "ans": false,
    "exp": "Ez hamis. A CES szélesebb kategória, mint a fogyatékosság – magában foglalhatja a tanulási zavarokat, a magatartási nehézségeket és a szociális hátrányból eredő igényeket is, tehát fogyatékossági diagnózis nélküli tanulók is beletartozhatnak.",
    "diff": 1
  },
  {
    "id": "w4_30",
    "w": 4,
    "topic": "Pszichopedagógia specialis feladatai",
    "type": "fill",
    "q": "A pszichopedagógia specialis megelőző feladata a másodlagos fogyatékosságok – például a szociális kirekesztés, a tanulási kudarcok halmozódása és az önértékelési problémák – megelőzésére irányul ____ felismeréssel és célzott beavatkozással.",
    "ans": "korai",
    "exp": "A megelőző feladat célja a másodlagos fogyatékosságok megelőzése korai felismeréssel és célzott beavatkozással.",
    "diff": 1
  },
  {
    "id": "w4_31",
    "w": 4,
    "topic": "Speciális oktatási módszerek",
    "type": "order",
    "q": "Rendezze helyes sorrendbe a PECS-alapú reggeli rutinfejlesztés lépéseit a fejlesztő tevékenység leírása alapján!",
    "items": [
      "A pedagógus azonnali megerősítéssel reagál és átadja a kért ételt/italt",
      "A tanuló rámutat vagy leveszi a kívánt képkártyát és átadja a pedagógusnak",
      "A pedagógus a reggeli előtt a tanuló elé teszi a kommunikációs táblát",
      "A pedagógus fokozatosan csökkenti a gesztus-segítséget és önálló kártyaátadásra bíztatja a tanulót"
    ],
    "exp": "A helyes sorrend: 1. A pedagógus elé teszi a kommunikációs táblát, 2. A tanuló rámutat vagy leveszi a képkártyát, 3. A pedagógus megerősítéssel reagál és átadja a kért dolgot, 4. A pedagógus fokozatosan csökkenti a segítséget.",
    "diff": 2
  },
  {
    "id": "w4_32",
    "w": 4,
    "topic": "Speciális oktatási módszerek",
    "type": "mc",
    "q": "Miért különösen fontos az utánzás (imitáció) szándékos fejlesztése ASD tanulóknál?",
    "opts": [
      "Mert ASD tanulóknál az imitáció spontán megjelenése korlátozott, ezért explicit megtanítása a fejlesztés alapeleme",
      "Mert ASD tanulók kizárólag utánzással képesek tanulni, más módszer nem alkalmazható",
      "Mert az utánzás kizárólag a motorikus készségek fejlesztésére alkalmas",
      "Mert ASD tanulóknál az imitáció teljes mértékben hiányzik, és soha nem fejleszthető"
    ],
    "ans": 0,
    "exp": "ASD tanulóknál az imitáció spontán megjelenése korlátozott, ezért az utánzásos tanulás szándékos fejlesztése és explicit megtanítása a fejlesztés alapeleme.",
    "diff": 2
  },
  {
    "id": "w4_33",
    "w": 4,
    "topic": "Módszertani adaptáció",
    "type": "mc",
    "q": "Hogyan kell adaptálni a magyarázat módszerét enyhe intellektuális fogyatékossággal élő tanuló számára?",
    "opts": [
      "Hosszabb, összefüggő magyarázatot kell alkalmazni, hogy az összképet láthassa",
      "Rövidebb egységekre kell tagolni, vizuális elemekkel kísérni, és rendszeresen visszakérdezni a megértés ellenőrzéseként",
      "Kizárólag szóbeli ismertetést kell alkalmazni, képi elemek nélkül",
      "Az ismeretlen szavakat meg kell tartani, hogy a szókincset fejlessze"
    ],
    "ans": 1,
    "exp": "Enyhe intellektuális fogyatékossággal élő tanuló esetén a magyarázat rövidebb egységekre tagolódik (max. 3–4 mondat), minden gondolati egységet vizuális elem kísér, rendszeresen visszakérdeznek a megértésről, és az ismeretlen szavakat konkrét fogalmakkal helyettesítik.",
    "diff": 2
  },
  {
    "id": "w4_34",
    "w": 4,
    "topic": "Logopédiai módszerek",
    "type": "short",
    "q": "Sorolja fel a fonémtudatosság-fejlesztő módszer (fonetikus-analitikus eljárás) jellemzőit és a 'Mi az első hang?' gyakorlat lépéseit!",
    "keywords": [
      "hangelemzés",
      "hangszintézis",
      "olvasás-írás",
      "képkártyák",
      "első hang",
      "csoportosítás"
    ],
    "exp": "A fonémtudatosság-fejlesztő módszer célja a hangelemzési és hangszintézis-képesség kialakítása, amely az olvasás-írás elsajátításának alapfeltétele. A 'Mi az első hang?' gyakorlatban: a logopédus képkártyákat mutat, a gyermek megnevezi a képet, meghatározza az első hangot (tapsolva vagy koronggal jelölve), majd vegyes képeket csoportosít az első hang szerint.",
    "diff": 2
  },
  {
    "id": "w4_35",
    "w": 4,
    "topic": "Komplex integrált oktatási terápia",
    "type": "mc",
    "q": "A szocioemocionális és viselkedéstámogató modul melyik területekre irányul?",
    "opts": [
      "A figyelem, emlékezet, gondolkodás és problémamegoldás célzott fejlesztésére",
      "A nagy- és finommotorika, a testséma és az önkiszolgálási készségek fejlesztésére",
      "Az érzelmi szabályozásra, a szociális készségekre, az önképre és a viselkedéstámogatásra (PBS)",
      "A beszéd, a nyelv és a kommunikáció fejlesztésére, augmentatív kommunikációra"
    ],
    "ans": 2,
    "exp": "A szocioemocionális és viselkedéstámogató modul az érzelmi szabályozás, a szociális készségek, az önkép és a viselkedéstámogatás (PBS) területeire irányuló beavatkozásokat foglalja magában.",
    "diff": 1
  }
];
