// Worksheet 5 exercises — generated by generate.js
// Source: gyakorlas_5_magoldasok_cl.docx
const EXERCISES_W5 = [
  {
    "id": "w5_01",
    "w": 5,
    "topic": "Etiológia alapfogalmak",
    "type": "mc",
    "q": "Mit vizsgál az etiológia a pedagógiai gyakorlatban?",
    "opts": [
      "A fogyatékosságok okait, eredetét és kiváltó tényezőit",
      "A gyermekek intelligenciájának mérési módszereit",
      "A tanterv fejlesztésének elveit és módszereit",
      "A nevelési intézmények szervezeti felépítését"
    ],
    "ans": 0,
    "exp": "Az etiológia a fogyatékosságok, zavarok vagy betegségek okait, eredetét és kiváltó tényezőit vizsgáló tudományág. Ismerete segíti a megelőzést, a korai felismerést és a célzott intervenciót.",
    "diff": 1
  },
  {
    "id": "w5_02",
    "w": 5,
    "topic": "Etiológia alapfogalmak",
    "type": "mc",
    "q": "Melyik az endogén ok példája az alábbiak közül?",
    "opts": [
      "Szülési trauma oxigénhiánnyal",
      "Anyai rubeolafertőzés az első trimeszterben",
      "Down-szindróma (trisomia 21)",
      "Bakteriális meningitis csecsemőkorban"
    ],
    "ans": 2,
    "exp": "Az endogén ok belső, az egyén biológiai adottságaiból eredő tényező. A Down-szindróma (trisomia 21) kromoszóma-anomália, tehát genetikai, belső ok. A többi felsorolt tényező exogén (külső) ursprungú.",
    "diff": 1
  },
  {
    "id": "w5_03",
    "w": 5,
    "topic": "Etiológiai tényezők",
    "type": "mc",
    "q": "Az anyai alkoholfogyasztás a terhesség alatt melyik etiológiai kategóriába tartozik?",
    "opts": [
      "Posztnatális exogén tényező",
      "Perinatális endogén tényező",
      "Prenatális exogén tényező",
      "Posztnatális endogén tényező"
    ],
    "ans": 2,
    "exp": "Az alkohol teratogén anyagként prenatálisan (születés előtt) hat a fejlődő magzatra, és külső (exogén) forrásból ered. Következménye a Magzati alkohol-spektrum zavar (FASD).",
    "diff": 1
  },
  {
    "id": "w5_04",
    "w": 5,
    "topic": "Etiológiai tényezők",
    "type": "mc",
    "q": "Melyik következmény kapcsolódik a perinatális asphyxiához?",
    "opts": [
      "Congenitalis süketség és szürkehályog",
      "Cerebrális paresis és intellektuális fogyatékosság",
      "Kontrollálatlan étvágy és elhízás",
      "Szociális szorongás és szenzoros érzékenység"
    ],
    "ans": 1,
    "exp": "A perinatális asphyxia (oxigénhiány a szülés során) az agyszövet hypoxiás károsodásán keresztül cerebrális paresist, intellektuális fogyatékosságot vagy érzékszervi sérülést okozhat.",
    "diff": 1
  },
  {
    "id": "w5_05",
    "w": 5,
    "topic": "Szindrómák jellemzői",
    "type": "mc",
    "q": "Melyik tünet jellemző a Fragile X-szindrómára a szociális viselkedés területén?",
    "opts": [
      "Kontrollálatlan étvágy és hyperphagia",
      "Hipotónia és motoros fejlődési késés",
      "Szemkontaktus-kerülés és szenzoros érzékenység",
      "Congenitalis süketség és szívfejlődési rendellenesség"
    ],
    "ans": 2,
    "exp": "A Fragile X-szindrómára jellemző a szociális szorongás, a szemkontaktus-kerülés, a szenzoros érzékenység (zajra, érintésre), a hiperaktivitás és az impulzivitás – részleges átfedéssel az ASD tünetképével.",
    "diff": 1
  },
  {
    "id": "w5_06",
    "w": 5,
    "topic": "Szindrómák jellemzői",
    "type": "mc",
    "q": "Mi jellemzi elsősorban a Prader–Willi-szindrómát az iskolai életben?",
    "opts": [
      "Súlyos látásfogyatékosság és mozgáskorlátozottság",
      "Kontrollálatlan étvágy és étkezési konfliktusok",
      "Teljes kommunikáció-képtelenség és autisztikus visszahúzódás",
      "Epilepsziás rohamok és memóriazavar"
    ],
    "ans": 1,
    "exp": "A Prader–Willi-szindróma egyik legjellemzőbb tünete a kontrollálatlan étvágy (hyperphagia), amely komoly egészségügyi kockázatot jelent és az iskolai étkezési szituációkban konfliktusokat okozhat.",
    "diff": 1
  },
  {
    "id": "w5_07",
    "w": 5,
    "topic": "Prevalenciaadatok pedagógiai jelentősége",
    "type": "mc",
    "q": "Miért fontos a prevalenciaadatok ismerete az oktatási rendszer tervezésekor?",
    "opts": [
      "Mert meghatározza az egyes tanulók egyéni fejlesztési céljait",
      "Mert segítségével meghatározható a várható CES tanulók száma és a szükséges szakemberigény",
      "Mert kötelező jogi dokumentumot képez minden iskolában",
      "Mert kizárólag a gyógypedagógiai szakszolgálatok számára releváns adat"
    ],
    "ans": 1,
    "exp": "A prevalenciaadatok alapvető tervezési eszközök: segítségükkel meghatározható, hogy hány CES tanulóval kell számolni, milyen szakemberigény várható, és milyen fejlesztő infrastruktúra szükséges.",
    "diff": 1
  },
  {
    "id": "w5_08",
    "w": 5,
    "topic": "Öröklés, környezet, nevelés",
    "type": "mc",
    "q": "Melyik állítás írja le helyesen az interakcionista modellt a fejlődéssel kapcsolatban?",
    "opts": [
      "Az öröklés egyedül határozza meg a fejlődés végeredményét",
      "A nevelés teljesen felülírja az öröklés hatásait",
      "Az öröklés, a környezet és a nevelés folyamatos kölcsönhatásban alakítja a fejlődést",
      "A környezet hatástalan, ha az öröklési adottságok kedvezőtlenek"
    ],
    "ans": 2,
    "exp": "Az interakcionista modell szerint az öröklés, a környezet és a nevelés nem egymástól függetlenül, hanem folyamatos kölcsönhatásban alakítja a fejlődést. Az öröklés a lehetőségek terét jelöli ki, de nem a végeredményt.",
    "diff": 1
  },
  {
    "id": "w5_09",
    "w": 5,
    "topic": "Kompenzációs fejlődés",
    "type": "mc",
    "q": "Mit ért Vigotszkij a kompenzációs fejlődés fogalmán?",
    "opts": [
      "A fogyatékosság teljes megszüntetését megfelelő terápiával",
      "A sértetlen funkciók mozgósítását a sérült funkciók hatásának ellensúlyozására",
      "Az egyén iskolai teljesítményének átlaghoz való igazítását",
      "A gyermek fogyatékosságának titokban tartását a kortársak előtt"
    ],
    "ans": 1,
    "exp": "Vigotszkij kompenzációs fejlődés fogalma azt a folyamatot írja le, amelynek során a fogyatékossággal élő személy meglévő, sértetlen funkcióit mozgósítja és fejleszti a sérült funkciók hatásának ellensúlyozására.",
    "diff": 1
  },
  {
    "id": "w5_10",
    "w": 5,
    "topic": "Kompenzációs fejlődés",
    "type": "mc",
    "q": "Melyik példa szemlélteti helyesen a kompenzációs fejlődést vakság esetén?",
    "opts": [
      "A látó funkció műtéti helyreállítása lézeres beavatkozással",
      "A taktilis és auditív percepció rendkívüli fejlődése Braille-írás és hallás útján",
      "A kognitív funkciók teljes leállása látásvesztés után",
      "A mozgásos kompenzáció kerekesszék segítségével"
    ],
    "ans": 1,
    "exp": "Vakság esetén a taktilis (tapintásos) és auditív percepció rendkívüli mértékben fejlődhet. A vak tanuló Braille-írás és hallás útján sajátítja el a szövegolvasást – ez a kompenzáció klasszikus példája.",
    "diff": 2
  },
  {
    "id": "w5_11",
    "w": 5,
    "topic": "Ontogenetikus fejlődési szakaszok",
    "type": "mc",
    "q": "Melyik életszakaszban a legnagyobb az idegrendszer fejlődési plaszticitása CES gyermekek esetén?",
    "opts": [
      "Serdülőkor (12–18 év)",
      "Kisiskoláskor (7–12 év)",
      "Csecsemő- és kisgyermekkor (0–3 év)",
      "Óvodáskor (3–7 év)"
    ],
    "ans": 2,
    "exp": "A csecsemő- és kisgyermekkor (0–3 év) az idegrendszer fejlődési plaszticitásának csúcsidőszaka. A korai azonosítás és fejlesztő beavatkozás ebben a szakaszban a leghatékonyabb.",
    "diff": 1
  },
  {
    "id": "w5_12",
    "w": 5,
    "topic": "CES fejlődési sajátosságok",
    "type": "mc",
    "q": "Mit jelent a generalizációs nehézség CES tanulók esetén?",
    "opts": [
      "A tanuló nem képes új szavakat megjegyezni",
      "Az egyik kontextusban elsajátított készség nehezen vihető át más helyzetbe",
      "A tanuló képtelen csoportos foglalkozásokon részt venni",
      "Az olvasási készség nem fejlődik ki általános iskolás korra"
    ],
    "ans": 1,
    "exp": "A generalizációs nehézség azt jelenti, hogy az egyik kontextusban elsajátított készség nehezen vihető át más helyzetbe. A tanultakat több, eltérő környezetben kell gyakoroltatni.",
    "diff": 2
  },
  {
    "id": "w5_13",
    "w": 5,
    "topic": "Curriculum fogalma és összetevői",
    "type": "mc",
    "q": "Mi tartozik a nemzeti curriculum 'rejtett curriculum' értelmezésébe?",
    "opts": [
      "A titkos minisztériumi dokumentumokban rögzített célok",
      "Az iskolai élet szövetéből elsajátított normák, elvárások és értékek",
      "A differenciált fejlesztési tervek tartalma",
      "A vizsgakövetelmények nem nyilvános szempontjai"
    ],
    "ans": 1,
    "exp": "A curriculum tágabb értelmezésben nemcsak a formálisan előírt tananyagot foglalja magában, hanem a rejtett curriculumot is – azokat a normákat, elvárásokat és értékeket, amelyeket a tanuló az iskolai élet szövetéből sajátít el.",
    "diff": 2
  },
  {
    "id": "w5_14",
    "w": 5,
    "topic": "Curriculumtípusok",
    "type": "mc",
    "q": "Melyik curriculumtípus jellemzője, hogy a tartalmakat önálló, lezárható, tetszőleges sorrendben elvégezhető egységekre tagolja?",
    "opts": [
      "Interdiszciplináris curriculum",
      "Adaptált curriculum",
      "Moduláris curriculum",
      "Differenciált curriculum"
    ],
    "ans": 2,
    "exp": "A moduláris curriculum az oktatási tartalmat önálló, lezárható és tetszőleges sorrendben elvégezhető egységekre (modulokra) tagolja, amelyek rugalmasan kombinálhatók.",
    "diff": 1
  },
  {
    "id": "w5_15",
    "w": 5,
    "topic": "Curriculumtípusok",
    "type": "mc",
    "q": "Miben különbözik az adaptált curriculum a differenciált curriculumtól?",
    "opts": [
      "Az adaptált curriculumban az általános célok azonosak maradnak, csak a módszer változik",
      "Az adaptált curriculumban a célok, tartalmak és teljesítménykritériumok is módosíthatók",
      "A differenciált curriculum kizárólag CES tanulók számára készül",
      "Az adaptált curriculum csak az értékelési szempontokon változtat"
    ],
    "ans": 1,
    "exp": "Az adaptált curriculum a többségi tantervtől eltérő, egyéni szükségletekre szabott oktatási terv, amelyben a célok, tartalmak és teljesítménykritériumok is módosíthatók. A differenciált curriculumban az általános célok azonosak maradnak.",
    "diff": 2
  },
  {
    "id": "w5_16",
    "w": 5,
    "topic": "Operacionalizált célok",
    "type": "mc",
    "q": "Melyik elem NEM része egy helyesen operacionalizált fejlesztési célnak?",
    "opts": [
      "Megfigyelhető viselkedés",
      "Teljesítménykritérium",
      "A tanuló szüleinek képzettsége",
      "Feltétel (körülmény, eszköz)"
    ],
    "ans": 2,
    "exp": "Az operacionalizált cél három kötelező eleme: a megfigyelhető viselkedés, a feltétel (körülmény, eszköz) és a teljesítménykritérium. A szülők képzettsége nem tartozik a fejlesztési cél összetevői közé.",
    "diff": 1
  },
  {
    "id": "w5_17",
    "w": 5,
    "topic": "Speciális curriculum sajátosságai",
    "type": "mc",
    "q": "Melyik állítás igaz a speciális curriculum egyénre szabottságával kapcsolatban?",
    "opts": [
      "A speciális curriculum egységes minden CES tanuló számára",
      "A PIP dokumentálja, és rendszeres – általában féléves – felülvizsgálat tárgyát képezi",
      "A speciális curriculum csak az akadémiai tárgyakra terjed ki",
      "A speciális curriculumot kizárólag a szülők dolgozzák ki"
    ],
    "ans": 1,
    "exp": "A speciális curriculum egyénre szabott: a tanuló funkcionális profiljára, erősségeire és szükségleteire épül. A PIP (Személyre szabott Intervenciós Program) dokumentálja, és rendszeres, általában féléves felülvizsgálat tárgyát képezi.",
    "diff": 1
  },
  {
    "id": "w5_18",
    "w": 5,
    "topic": "Énkép és motiváció",
    "type": "mc",
    "q": "Mit jelent az 'elsajátított tehetetlenség' (learned helplessness) fogalma CES tanulók esetén?",
    "opts": [
      "A tanuló fizikai mozgáskorlátozottságát a mindennapi életben",
      "A tartós sikertelenség hatására kialakuló passzivitás és motivációhiány",
      "A kognitív funkciók veleszületett korlátozottságát",
      "A tanár túlzott segítségnyújtását minden feladatnál"
    ],
    "ans": 1,
    "exp": "Az elsajátított tehetetlenség (learned helplessness) komoly kockázat, ha a fejlesztés nem épít sikerélményekre. Az ismételt iskolai kudarcok hatására a tanuló elveszíti hitét saját képességeiben, és passzívvá válik.",
    "diff": 2
  },
  {
    "id": "w5_19",
    "w": 5,
    "topic": "Etiológia alapfogalmak",
    "type": "tf",
    "q": "A rizikótényező önmagában mindig fogyatékosságot okoz a gyermekben.",
    "ans": false,
    "exp": "Hamis. A rizikótényező olyan körülmény, amely önmagában nem feltétlenül okoz fogyatékosságot, de jelentősen növeli annak valószínűségét. Például a koraszülöttség rizikótényező, de nem minden koraszülött gyermeknél alakul ki fogyatékosság.",
    "diff": 1
  },
  {
    "id": "w5_20",
    "w": 5,
    "topic": "Korai felismerés és prevenció",
    "type": "tf",
    "q": "Az idegrendszer fejlődési plaszticitása a korai életévekben a legnagyobb, ezért a korai fejlesztés eredményei felülmúlják a késői intervenció hatásait.",
    "ans": true,
    "exp": "Igaz. A korai felismerés és beavatkozás hatékonysága az idegrendszer korai plaszticitásán alapul. Minél korábban azonosítják a fejlődési eltérést, annál hatékonyabb lehet a beavatkozás.",
    "diff": 1
  },
  {
    "id": "w5_21",
    "w": 5,
    "topic": "Szindrómák jellemzői",
    "type": "tf",
    "q": "A Prader–Willi-szindrómás tanulók erős vizuális-téri képességekkel rendelkeznek, amelyek tanítási erőforrásként hasznosíthatók.",
    "ans": true,
    "exp": "Igaz. A Prader–Willi-szindrómában enyhe–közepes intellektuális fogyatékosság mellett erős vizuális-téri képességek jellemzők. A pedagógiai következmény szerint a vizuális erősségeket a tanítás gerincévé kell tenni.",
    "diff": 2
  },
  {
    "id": "w5_22",
    "w": 5,
    "topic": "Curriculumtípusok",
    "type": "tf",
    "q": "Az interdiszciplináris curriculum lerombolja a hagyományos tantárgyi határokat, és több tantárgy tartalmát integrálja egyetlen tanulási egységbe.",
    "ans": true,
    "exp": "Igaz. Az interdiszciplináris curriculum több tantárgy tartalmát és szemléletmódját integrálja egyetlen, összefüggő tanulási egységbe, lebontva a hagyományos tantárgyi határokat.",
    "diff": 1
  },
  {
    "id": "w5_23",
    "w": 5,
    "topic": "Öröklés, környezet, nevelés",
    "type": "tf",
    "q": "Fogyatékosság esetén az öröklési adottságok teljesen meghatározzák a fejlődési lehetőségeket, és a nevelés nem képes kompenzálni a biológiai hátrányokat.",
    "ans": false,
    "exp": "Hamis. A nevelés – különösen a korai speciális fejlesztés – képes kompenzálni a biológiai adottságok hátrányait. Vigotszkij elmélete és a neuroplaszticitás kutatásai szerint a fogyatékosság ténye nem határolja be a fejlődési lehetőségeket, csupán meghatározza a szükséges támogatás jellegét.",
    "diff": 2
  },
  {
    "id": "w5_24",
    "w": 5,
    "topic": "Etiológiai tényezők",
    "type": "fill",
    "q": "A szülés körüli időszakban fellépő oxigénhiány következtében kialakuló agysérülést ____ nevezzük.",
    "ans": "perinatális asphyxia",
    "exp": "A perinatális asphyxia az oxigénhiány a szülés során, amely az agyszövet hypoxiás károsodásán keresztül cerebrális paresist, intellektuális fogyatékosságot vagy érzékszervi sérülést okozhat.",
    "diff": 1
  },
  {
    "id": "w5_25",
    "w": 5,
    "topic": "Kompenzációs fejlődés",
    "type": "fill",
    "q": "Vigotszkij szerint a kompenzációs fejlődés során a fogyatékossággal élő személy ____ funkcióit mozgósítja a sérült funkciók hatásának ellensúlyozására.",
    "ans": "sértetlen",
    "exp": "A kompenzációs fejlődés lényege, hogy a személy meglévő, sértetlen funkcióit mozgósítja és fejleszti a sérült vagy hiányzó funkciók hatásának ellensúlyozására.",
    "diff": 1
  },
  {
    "id": "w5_26",
    "w": 5,
    "topic": "Speciális curriculum sajátosságai",
    "type": "fill",
    "q": "A speciális curriculum esetén az előrehaladás nem évfolyamhoz, hanem a tanuló egyéni ____ üteméhez kötött.",
    "ans": "fejlődési",
    "exp": "A speciális curriculum sajátossága a lassabb tempó és fokozatosság: az előrehaladás nem évfolyamhoz, hanem a tanuló egyéni fejlődési üteméhez kötött.",
    "diff": 1
  },
  {
    "id": "w5_27",
    "w": 5,
    "topic": "Etiológia alapfogalmak",
    "type": "match",
    "q": "Párosítsd össze az etiológiai fogalmakat a helyes meghatározásukkal!",
    "pairs": [
      {
        "L": "Endogén ok",
        "R": "Belső, genetikai vagy biológiai adottságból eredő tényező"
      },
      {
        "L": "Exogén ok",
        "R": "Külső, környezetből érkező, fejlődést kedvezőtlenül befolyásoló tényező"
      },
      {
        "L": "Rizikótényező",
        "R": "Önmagában nem okoz fogyatékosságot, de növeli annak valószínűségét"
      },
      {
        "L": "Szindróma",
        "R": "Tünetek olyan együttese, amely rendszeresen együtt jelenik meg és felismerhető klinikai képet alkot"
      }
    ],
    "exp": "Az endogén ok belső (pl. genetikai) tényező, az exogén ok külső (pl. anyai fertőzés). A rizikótényező növeli a valószínűséget, de nem okoz egyértelműen fogyatékosságot. A szindróma tünetek jellegzetes együttese.",
    "diff": 1
  },
  {
    "id": "w5_28",
    "w": 5,
    "topic": "Szindrómák jellemzői",
    "type": "match",
    "q": "Párosítsd össze a szindrómákat azok egyik legjellemzőbb tünetével!",
    "pairs": [
      {
        "L": "Down-szindróma",
        "R": "Izomtónus csökkentség (hipotónia)"
      },
      {
        "L": "Fragile X-szindróma",
        "R": "Szenzoros érzékenység és szemkontaktus-kerülés"
      },
      {
        "L": "Prader–Willi-szindróma",
        "R": "Kontrollálatlan étvágy (hyperphagia)"
      },
      {
        "L": "Landau–Kleffner-szindróma",
        "R": "Szerzett szindróma (nem genetikai eredetű)"
      }
    ],
    "exp": "Down-szindróma: hipotónia; Fragile X: szenzoros érzékenység, szemkontaktus-kerülés; Prader–Willi: hyperphagia; Landau–Kleffner: szerzett szindróma. Ezek az egyes szindrómák legjellemzőbb jegyei a tananyag alapján.",
    "diff": 2
  },
  {
    "id": "w5_29",
    "w": 5,
    "topic": "Ontogenetikus fejlődési szakaszok",
    "type": "order",
    "q": "Rendezd sorrendbe a CES gyermekek ontogenetikus fejlődési szakaszait a legkorábbbitól a legkésőbbiig!",
    "items": [
      "Csecsemő- és kisgyermekkor (0–3 év) – korai fejlesztés szakasza",
      "Óvodáskor (3–7 év) – szocializáció és iskolai előkészítés",
      "Kisiskoláskor (7–12 év) – iskolai tanulás és kompetenciafejlesztés",
      "Serdülőkor – identitás és önállósodás szakasza"
    ],
    "exp": "A helyes sorrend: 1. Csecsemő- és kisgyermekkor (0–3 év), 2. Óvodáskor (3–7 év), 3. Kisiskoláskor (7–12 év). A tananyag ezt a három szakaszt tárgyalja részletesen CES kontextusban.",
    "diff": 1
  },
  {
    "id": "w5_30",
    "w": 5,
    "topic": "Operacionalizált célok",
    "type": "order",
    "q": "Rendezd sorrendbe az operacionalizált fejlesztési cél alkotóelemeit a logikus leírás sorrendjében!",
    "items": [
      "A tanuló azonosítása és a fejlesztési terület megnevezése",
      "A feltétel (körülmény, eszköz, helyszín) meghatározása",
      "A megfigyelhető viselkedés pontos leírása",
      "A teljesítménykritérium és az időkeret megjelölése"
    ],
    "exp": "A helyes sorrend egy operacionalizált cél felépítésekor: 1. tanuló és terület azonosítása, 2. feltétel meghatározása, 3. megfigyelhető viselkedés leírása, 4. teljesítménykritérium és időkeret. Ez felel meg a három kötelező összetevő (feltétel, viselkedés, kritérium) logikus leírásának.",
    "diff": 2
  },
  {
    "id": "w5_31",
    "w": 5,
    "topic": "Prevenció és multidiszciplinaritás",
    "type": "short",
    "q": "Sorold fel a multidiszciplináris team legalább négy szakemberét, akik részt vesznek a CES tanulók komplex értékelésében és fejlesztésében!",
    "keywords": [
      "gyermekorvos",
      "pszichológus",
      "gyógypedagógus",
      "logopédus"
    ],
    "exp": "A tananyag szerint a multidiszciplináris team tagjai: gyermekorvos, neurológus, pszichológus, gyógypedagógus, logopédus, foglalkozásterapeuta és szociális munkás. Az összehangolt munka biztosítja a holisztikus megközelítést.",
    "diff": 2
  },
  {
    "id": "w5_32",
    "w": 5,
    "topic": "Etiológiai tényezők",
    "type": "mc",
    "q": "Melyik posztnatális tényező okozhat siketséget, epilepsziát és intellektuális fogyatékosságot?",
    "opts": [
      "Koraszülöttség (28 hét előtt)",
      "Anyai rubeolafertőzés az első trimeszterben",
      "Bakteriális meningitis csecsemőkorban",
      "Alkohol a terhesség alatt (FASD)"
    ],
    "ans": 2,
    "exp": "A bakteriális meningitis (agyhártyagyulladás) csecsemőkorban posztnatális tényező, amely az agyszövet gyulladásos károsodásán keresztül siketséget, epilepsziát, intellektuális fogyatékosságot vagy mozgásfejlődési elmaradást okozhat.",
    "diff": 2
  },
  {
    "id": "w5_33",
    "w": 5,
    "topic": "Prevalenciaadatok pedagógiai jelentősége",
    "type": "mc",
    "q": "Melyik az egyik legfontosabb értelmezési korlátja a prevalenciaadatoknak?",
    "opts": [
      "A prevalenciaadatok kizárólag fejlett országokban érvényesek",
      "A diagnosztikai kritériumok és a kulturális különbségek befolyásolják az adatokat",
      "A prevalencia kizárólag genetikai tényezőktől függ",
      "A prevalenciaadatok mindig pontosan tükrözik a valós előfordulást"
    ],
    "ans": 1,
    "exp": "Az egyik értelmezési korlát: a prevalenciaadatok erősen függenek az alkalmazott diagnosztikai rendszertől (DSM-5, ICD-11) és a diagnosztikai hozzáférés egyenletességétől. Ugyanaz az állapot más arányban kerül azonosításra eltérő környezetekben.",
    "diff": 2
  },
  {
    "id": "w5_34",
    "w": 5,
    "topic": "CES fejlődési sajátosságok",
    "type": "mc",
    "q": "Melyik CES fejlődési sajátosság kapcsolódik az 'alacsonyabb frusztrációs tolerancia' fogalmához?",
    "opts": [
      "A generalizációs nehézség más kontextusban",
      "Az érzelmi szabályozás éretlensége, amikor kisebb akadályok is intenzív reakciókat váltanak ki",
      "A lassabb tanulási tempó és a nagyobb ismétlésigény",
      "A szociális készségek fejlődési elmaradása"
    ],
    "ans": 1,
    "exp": "Az alacsonyabb frusztrációs tolerancia és érzelmi labilitás azt jelenti, hogy – különösen intellektuális fogyatékosság, ASD vagy ADHD esetén – az érzelmi szabályozás éretlensége jellemző, és kisebb akadályok is intenzív érzelmi reakciókat válthatnak ki.",
    "diff": 1
  },
  {
    "id": "w5_35",
    "w": 5,
    "topic": "Énkép és motiváció",
    "type": "mc",
    "q": "Melyik tényező erősíti az autonómia érzését és a belső motivációt CES tanulóknál?",
    "opts": [
      "A tanár által kizárólagosan meghatározott fejlesztési célok",
      "Az életkornak megfelelő döntési lehetőségek biztosítása a tanulónak",
      "A teljes feladatmentesítés a kudarc elkerülése érdekében",
      "A kortársaktól való teljes elszigetelés a nyugodt tanuláshoz"
    ],
    "ans": 1,
    "exp": "A tanuló számára életkorának és képességeinek megfelelő döntési lehetőségek biztosítása (pl. feladatválasztás, munkaeszköz meghatározása) csökkenti a tehetetlenség élményét, erősíti az önszabályozást és a belső motivációt.",
    "diff": 2
  }
];
